from .main import part1, part2


INPUT = """\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""


def test_part1():
    assert part1(INPUT) == 21


def test_part2():
    assert part2(INPUT) == 40


def test_input():
    with open("input.txt") as file:
        input = file.read()

    assert part1(input) == 1560
    assert part2(input) == 25592971184998
